### ISSUE TITLE
hash codes of 4 roms don't match

### ISSUE THREAD

**Issue by Robbbert** [jessaskey/mhavocpe#102]
The CRC/SHA1 of mhpe.1mn, 1l, 1q, 1np do not match the HBmame pull request. It appears those roms were updated after the PR was submitted. Should I just use the new hashes that HBmame has provided? The game appears to work.

**Comment by jessaskey** [comment]
Okay, Im getting this figured out, we had a handful of bugs in that 0.50 release and im now on 0.52 after bugfixes... after a couple more days of 'all clear', then I will update the code and pull request code to match the 'final' CAX ROMset. thank you for pointing this out!
