### ISSUE TITLE
0.50 Romset - Can't Select Demo Mode from Self Test

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#103]
In HBMAME I wasn't able to activate Demo Mode from Self Test. You can select Demo Mode but when you press shield twice to confirm it jumps back to Hard Diff.

We still want to allow people to explore all the new levels so Demo Mode should be included and working (and at medium difficulty so it plays the same as Factory Default in the mazes otherwise).

**Comment by jessaskey** [comment]
I forgot about this issue that we saw at CAX... thanks for logging it. Im going to fix this today hopefully and cram it into a new 0.50 release and get that version pushed into the Editor as well. Hold tight.

**Comment by jerkyspace** [comment]
Fixed thanks!

**Comment by jessaskey** [comment]
Re-Fixed in Release 0.51
