### ISSUE TITLE
Get rid of the super fast shot that outerspace fighters make on higher levels

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#105]
Another thing we all saw and talked about at CAX 2019.

On the higher levels the Fighters on the 2nd and 4th levels (Star Castle Battle on L21 too) will occasional fire a super fast shot (just after their normal grouping of slower shots) that the player cannot possibly dodge. It also seems it evades collision detection occasionally as well making it even more random and unfair.

**Comment by jessaskey** [comment]
Okay, I *think* I found the fast shot. This will be fixed in 0.53 release, but Jerky you will have to tell me if you see that shot still happening.
