### ISSUE TITLE
Dial back the difficulty of the 4th outer-space "boom" waves

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#106]
On the higher levels the angry red lines are just too angry while the fighters too fast and hard to deal with (also has the super fast shot issue). These waves need to be a little more reasonable because it seems like a miracle to get through without dying sometimes from Level 16+.

Slightly slower red lines (booms) and dial the fighter movement speed and shots back just a bit and this will be much more reasonable.

We need more clones for the mazes after all ;)

**Comment by jessaskey** [comment]
I dug into this a little and from what I can tell, the fighters don't have a speed increase at all in the 'Type D' space wave (fighters with red bar). Im looking at the Red Bar code now to see how that works.

**Comment by jessaskey** [comment]
Okay, I found the code for this, velocity of fighters was the same, but the shot speed did increase. This is actually the same issue as Issue#105. I tweaked the speed down a little more with a small increase to make this smoother and also much less steep.
