### ISSUE TITLE
Romset 0.51 and Editor v1.1.959 production roms using wrong maze collection

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#109]
The mhavocpe_jerky_officia.mhc that I used to make those recent playback vids from the Github site has the correct post CAX maze collection edits I made....but the new romset 0.51 and editor do not.
https://github.com/jessaskey/mhavocpe/blob/master/Levels/mhavocpe_jerky_official.mhc

The last Editor version's production roms were not updated to the official mhc you put on github and I think you used those to make the 0.51 romset and editor 1.1.959.0 production roms that are both missing the 4th IonCannon I added to level 22 for example (IonCannon1 in the mhavocpe_jerky_official.mhc collection located just to the left of Transporter35 ).

**Comment by jessaskey** [comment]
Updated in Release 0.52 with file version "MHPE 119641 08172019.mhc"
