### ISSUE TITLE
Level 22 TripPad64 firing faster + Running out of o2 too soon

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#115]
0.52 romset
0.209, 0.212 and 0.213 HBMAME

When playing via HBMAME TripPad64 and it's Pyroid/Fryoid64 is firing shots faster than when you play in the editor (1.2.986.2). It catches the player from behind too soon before they can escape into the next upper hallway (kills them right at TripPad66 instead of being slower and allowing them to escape upwards).

I have not made any changes to this level for some time so not sure what is causing this. Again I was playing from level 1 checking the 0.52 romsets when i ran across this today.

When you use Demo mode and play from Level 21 the speed is normal (like the Editor too).

I found a way to get past this issue above and still stay on pattern but then i kept running out of o2 too soon which I should have plenty of. I am also having the same screen blankout bug that keeps me from seeing the oxygen value and maze map scanner borders (when I go back to check with save states). 

Again no oxygen issues when playing in the Editor or using Demo mode to play from level 21 or 22 forward. Only when playing from level 1 to here. Weird.

**Comment by jerkyspace** [comment]
It seems like the latest version of HBMAME 0.212 is the problem. I tested the same romset 0.52 and didn't see any of the issues I did on Levels 1-3 so far. I can guess it will be the same for the problems I had on Levels 21-22.

Testing the rest of the levels out in 0.209 and will report back. Making a note that 0.212 HBMAME causes problems.

**Comment by jerkyspace** [comment]
This is may be due to changes in newer HBMAME versions 0.212 and 0.213 (save states only). I am testing with 0.209 and will report back. Closing for now.

**Comment by jerkyspace** [comment]
Reopened.

It does this with version 0.209 too. When you play from Level 1 to 22 now the oxygen either runs out too fast or the reward value to start is wrong. So you run out of o2 on the way to the Cyan key and cant get back to the reactor now. 

The same TripPad Pyrod/Fryoid is also moving faster and catches the player by the second stalactite instead of being slower and allowing them to escape.

Doesn't do this in the Editor nor from Demo mode. Only when you play from level 1 forward. You can't get past level 22 as it is with these issues.

**Comment by jessaskey** [comment]
Going to track this under #150
