### ISSUE TITLE
HBMAME save state issues ::: 0.212 and 0.213

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#116]
0.52 romset
HBMAME 0.212 and 0.213

The latest version of HBMAME are causing several issues that you will only see when using save states it turns out (maze scanner borders and walls missing; objects offset outside maze borders; missing oxygen values; oxygen running out too fast; missing reactor countdown values).

0.212 keeps the objects in the maze scanner where they belong but in 0.213 when you come back to save states the objects are offset outside the maze partially sometimes like on 1-3 and 21-22 (scanner only not actual maze game play).

When you go back to a previous save state after you exit HBMAME you may see these issues that in some cases "break" levels like 22.

As far as I can tell save states are working fine in HBMAME 0.209 but I will keep testing (levels 1-3 check out). Not sure what they MAME folk changed but I have been able to reproduce  it every time on levels 1-3 and 21-22 with both these recent versions.

For now stick to HBMAME 0.209.

**Comment by jessaskey** [comment]
So, something to keep in mind between the mhavocpe builds (v0.49,v0.50,v0.51,v0.52 etc).... the memory locations often shift around between builds. The reason this happens has to do with the variables in the havoc code and the way they are allocated. If a new variable is added, it may 'shift up' the older memory parameters... and the opposite may also be true, if I remove an unused memory variable, then the other locations above it will 'shift down'.... what that means is that if you have save states from lets say v0.50 and try to use that save state on a v0.53 ROM set, then MAME will be putting data into the wrong memory locations and so it will basically become unusable.

This is an unfortunate side effect of recompiling but it does happen quite a bit and I would actually guess that more often than not, the memory is different across mhavocpe versions so I wouldn't rely on save states working from version to version.

**Comment by jerkyspace** [comment]
This is save states within the same version which usually work fine. I don't expect ones from different version to work for the reasons you state. I wouldn't worry about it too much since it seems to be on the HBMAME side and doesn't affect normal gameplay.

**Comment by jessaskey** [comment]
Closing this one.. if it creeps back up after we remove AD and the RAM variables are solid again (after v0.61) then we can reopen or create a new issue.
