### ISSUE TITLE
Game doesn't load Level 1 properly after you finish Level 24

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#117]
0.52 romset
HBMAME 0.209

I meant to mention this....after you finish Level 24 the heads up display shows the animation for the 4th wave "space fort" instead of the 1st one. It then lands you on a broken level 1. These levels should also be random colors right?

**Comment by jessaskey** [comment]
Here is the sequence of how this will be working...

1. Finish Final Supa-Station (Levels 21-24 combined into one giant maze).
2. If player dies after triggering reactor, you will have to start over. No Freebies per Owen and Im calling this the Groundhog Day Maneuver.
3. After sucessfully existing the final space station it will go into a VAXX bonus screen where the player is awarded points for finishing the station (100,000)... extra points for each life remaining (x 20K each)... and extra points for each Tesseract collected (x 25K each). 
4. Homeworld animation sequence... TBD.. working with Owen on this still.
5. End Story and music + fireworks.
6. Back to HUD Display for Level 1, with some notable changes tho..
- Random Maze Colors like post level 17 stuff in the original game
- Random Level messages now from Owen (funny)
- 1 step increased difficulty (like AD used to be, but now for all 24 levels. If you happen to finish it again, then difficulty will increase again.
