### ISSUE TITLE
Level 22/23 Red Door does not appear where it's drawn in HBMAME

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#120]
0.53 romset
1.2.998.0 Editor
0.209 HBMAME
Testing within the Editor

I have been trying to place the Red Door (now Lock 1) outside the Level 22 maze as Jess instructed so it won't be draw in a specific X location (high byte 00xx). But no matter where I place it on the whole available Y axis it ends up on the other side of the maze at  x=10xx (at the same Y position).

So if I place it in the Editor at 0x0080, F680 it appears at 0x1080, F680. If it is drawn at 0x0080, FB80 it ends up at 0x1080, FB80 when you play the maze back in HBMAME (0.209).

I already tried deleting the door and adding it again so it became a different Lock # and no change. I removed a few other random maze objects and it didn't change anything either. I cheeked to see if there were any weird empty wall objects outside the maze but couldn't find any.

I just ran into the same issue on Level 23 (Red Door/Lock34). It's the same issue : Draw it at X=00xx and it ends up at X=10xx at the same Y position (moves from far left of maze to far right when you play back in HBMAME).

**Comment by jessaskey** [comment]
I figured out this issue and it looks like it is going to affect any object that used the 'compact' form of positioning... that means locks and keys cant be hidden using this method. Im going to put this into the 0.55 release and figure it out later so I can get 0.54 released today for you to check out with the other changes you made in your .mhc master file too.

**Comment by jessaskey** [comment]
This need to be in the right half of the 00 (X axis) position otherwise they will 'snap' over to the other side. I will see if I can duplicate this in 0.68 ROM's and then close if not.

**Comment by jessaskey** [comment]
Okay, so objects that need to be hidden like this just need to be outside the maze on the right side. Looks like most of the designs do this now so I will close this issue.
