### ISSUE TITLE
Make reactors on Level 21-23 invisible on maze map too

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#121]
0.53 romset
1.2.998.0 Editor
0.209 HBMAME

The reactors on Level 21-23 are no longer visible outside the maze when placed at X = 00xx, but you can still see the yellow flashing dot for them at that location on the maze scanner at the top of the screen.

**Comment by jessaskey** [comment]
Okay, I think this is now fixed in the 0.54 release.
