### ISSUE TITLE
Key Pouch Keys not carrying over to next level (maze 4>5 test)

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#127]
Maybe it's because I am playing from level 2-4+ in the Editor but after you pick up the currently invisible key pouch on level 2 it doesn't carry keys over to the next level. I played from maze 2-5 and didn't use the two keys on the doors on level 4 (yellow/cyan). No blue and cyan keys on level 5 shown in my inventory (maybe invisible too like the pouch?).

**Comment by jessaskey** [comment]
Actually, maybe I didn’t document this very well, but I don’t think that there is any code in place to actually carry the keys forward when you have the pouch or maybe there is a bug in there. Either way, this is a solid bug so I will see about getting it done in 0.56…. do you feel you need this for Grinkfest?

**Comment by jerkyspace** [comment]
Yea I wasn't sure how much you had done yet but thought I should bring it up anyway just in case. WIP ;)

I wouldn't worry about the Key Pouch for Grinkfest since it's currently a very extra credit item for players that "need" to use extra keys to advance farther into the game by skipping sections of later mazes (sacrificing oxygen bonus points on the levels the save keys from they way I have it set up now). 

It will be a good chance to show it off to some of the right people between the Aurcade folk who run classic arcade tournaments around the country, a bunch of hardcore KLOV collectors , and some of the more active pro CAG players on the west coast.

**Comment by jessaskey** [comment]
closing this as we aren't going to use the keypouch
