### ISSUE TITLE
Level 3 - Star Castle battle instead of outer space maze

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#129]
0.56 romset
Factor Default Dips
Playing from Level 1 to 3

After you play the breakout game at the HUD for the start of Level 3 it jumps right into the Star Castle battle from level 21 instead of the outer space maze (from "You Will Not Win" into the battle). It does show the Level 3 maze correctly at the HUD though (and says it's level 3).

At first the fighters act like sections of the wall and they come out much faster filling the screen quickly. Then after you die once you can shoot them and the walls normally...but when you beat the Cube it loads level 1 again (not 3 or 21) + shows the Cube landing sequence instead of the normal level 1 (white cube versus green starbase). The level 1 maze is still green though.

Then after you beat the level 1 maze it goes back to the Level 1 fishoid outer space level again...then back to level 1 maze....and repeat.

Weirdness.

**Comment by jerkyspace** [comment]
Does the same thing in Demo mode if you go right to Level 3. Instead of the outer space maze you get the level 21 Star Castle battle that leads back to level 1 looping,

**Comment by jerkyspace** [comment]
It plays normal in Demo mode from level 4...until you get to Level 6 and try to access the hidden level. See other issue on this but after the 1st hidden level is played it goes to Level 7 which again loads a Cube star castle battle instead of the outer space maze.
https://github.com/jessaskey/mhavocpe/issues/130

**Comment by jerkyspace** [comment]
From Demo mode if you go right to Level 7 it loads a Cube space battle instead of the outer space maze just like level 3. At least it's consistent ;)

**Comment by jerkyspace** [comment]
Confirmed. All outer space mazes are being replaced with the Cube star castle battle from level 21. They loop back to the first level of that cycle of 4 and then after you beat that maze they all load Level 1 again.

So Level 3, 7, 11, 15 and 19 all go back to 1,5,9 and 13 after the level 21 space battle inserts itself but then revert to level 1 when you complete that maze (1,5,9 or 13). And it loops level 1 from there.

Super weirdness.

**Comment by jessaskey** [comment]
Okay, digging into this one now... sounds like a good one.

**Comment by jerkyspace** [comment]
Same problem in both 056a roms I got this AM.

Go fish ;)
