### ISSUE TITLE
Outerspace battles playing b4 hidden level mazes

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#131]
0.57 (fixed)
FPGA

So after you get a hidden token and the teseract hud/warp happens it doesn't play the maze....it plays the outerspace battle (4th cycle one with red lines I think?)

After the battle you land on the starbase and then the correct hidden level plays.

**Comment by jerkyspace** [comment]
0.57 fixed
HBMAME 0.209

Confirmed. Same behavior found in HBMAME. Ex. A  starbase and double angry red line outer-space battle starts in the background with fighters already spawned as the Tesseract screen and blue warp are triggered by the Level 6 hidden token. Then you have to get through the space battle before you get to the hidden level (difficulty seems maxed as well).

**Comment by jessaskey** [comment]
Okay, this makes better sense to me now as I was only testing play up through level 4-5 so I just hadn't gotten far enough to make this happen. I will investigate these this week and get something out that attempts to sorta get this whole 'teseract' thing cleaned up! Thank you!

**Comment by jerkyspace** [comment]
0.58 Romset
HBMAME 0.209

So after you get the Alpha Tesseract on Level 6 it still plays the 4th outerspace base battle before you can play the secret level maze (double red line too and high level of difficulty). Love the new warp colors.

I also noticed that you can start to play the breakout game for a moment b4 the alpha tesseract screen comes up.

Same problem with Level 10 after you get the Beta Tesseract...two angry red lines right on top of the player in outerspace battle that should not be happening prior to secret level (same super hard difficulty too).
