### ISSUE TITLE
Hidden Level Hud, Teseract Animation and Warp are playing b4 normal outerspace battles (fishoids, fighters, maze, starbase)

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#132]
0.57 (fixed)
FPGA

The hidden level hud, animation and warp keep popping up instead of the normal hud screens at the start of levels. This seems random. It can even happen before you play the fishoids on level 1. 

Unfortunately too the space battles starts playing in the background while the hidden level hud runs its cycle so when it ends the player often has fighters right on top of them or shots from them killing them off.

This is happening all over the place but not consistently. I saw it happen on levels from 1-20.

**Comment by jerkyspace** [comment]
If I recall right I did not see this behavior until AFTER I played up to and through Level 6 hidden level. It was subsequent games that this problem came up on. Maybe trigger hidden levels once or more than once is the root cause in subsequent games?

**Comment by jessaskey** [comment]
Okay, I have found and fixed this... it wouldn't happen until Level 6 when a 'hidden' token was on the maze, and then it was never being reset, which caused it to happen on every level. This will be fixed in the next release which I will get out this week/weekend.
