### ISSUE TITLE
Instability issues when you start second game

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#133]
0.57
HBAME 0.209
First played one game thru level 1-7 including triggering first Hidden level (played through it) then killed my game at the space maze off and re-started...

So after you play one game and die off and start a second one there are weird problems that come up :

Score starts out very high with hex values but then drops down to 100,000 for starting level 1 (A0A90000).

Graphics in center of HUD are all messed up (no fishoid starbase).

Hold Jump Button for Higher Jumps message across center of screen.

Then instead of Fishoids it goes to the Level 21 star castle battle.

After that it gives you a very slow Cube landing sequences (level 1 speed) and the game locks up before it plays whatever maze it was going to (stuck at fighter landing and about to zoom to maze).

Never saw this on the FPGA version at Grinkers.

**Comment by jessaskey** [comment]
I tested this out in the v0.58 build a little differently but it should have caused the same issue... I had the hidden level tesseract on Level 1 in this case and triggered the wormhole. I started another game and didn't see this happen. Im thinking that a bunch of cleanup around the initialization solved this as well so Im going to mark it complete int the v0.58 release and we can track it (or reopen this issue) if it is still around after v0.58.
