### ISSUE TITLE
Level 10 - Everything sped up

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#137]
0.58
HBMAME 0.209

So I went back and checked the editor.....the reactor is counting down way too fast on level 10 as is o2 consumption (when you play for 1-10).

Is this an adaptive diff issue and how do we fix it? There is barley enough reactor time and very little o2 left compared to what I see in the editor.

I was going to add more reactor time but don;t want to chase these AD issues around for months. WYSIWYG is what I am hoping for at least with o2 and reactor timing,,,,outside of objects that already had incremental velocity values programmed originally of course.

If the speed ups are consistent and I know where they are I can adjust for it if need be.

**Comment by jessaskey** [comment]
Let me dig into this Adaptive Difficulty thing... I agree with you, it makes things not WYSIWYG, so Im going to make a task to just basically take it away... this will help with consistency, plus make the game overall easier which keeps us moving in Owen's direction for his wants.

One of the side effects of this is that some of the classic levels which typically were faster (levels 5-12) should also slow down a bit. I will report back in this thread as I get into the code more too.

**Comment by jessaskey** [comment]
Going to track this under #150
