### ISSUE TITLE
Adaptive diff being added to Level 26 Trippads?

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#138]
So the player should be able to get by the two trip pads at the bottom of Level 26 just by running all the way to the right over both of them and heading up (83+84).....but when you play from Level 1-10 and make it to this secret level they are sped up so much that you get killed by them almost right away.

Right now it's very hard to get past the 2nd trip pad on this level (84) with it sped up like this. The other trip pads all seem to but one speed faster as well messing up the pattern for them near the Maxoid.

Oxygen consumption is sped up as well. Can't finish the level as it is now (playing from 1>10>26) but works fine in the editor.

This may have something to do with the outerspace level playing right before this also at a sped up/high diff level....?

**Comment by jessaskey** [comment]
Going to track this under #150
