### ISSUE TITLE
Level 15 - Particle Token shown in inventory from start of the level

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#139]
0.58 romset
HBMAME 0.209

When you start level 15 the Particle token found on Level 18 shows up in your "inventory" at the top left of the screen (playing from l1>15 including all previous hidden levels up to this point).

When you finish level 15 everything works normally. No hidden level. It goes right to Level 16 like it should.

Just an inventory ghost/glitch the game ignores.

**Comment by jessaskey** [comment]
Im pretty sure that this was an issue with the early versions of the tesseract tokens. I just tried in on Editor 1.3.0.0 and ROMs v0.63 and all was okay. Im going to mark this closed for now.
