### ISSUE TITLE
Level 28 - TripPads sped up

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#140]
0.58
HBMAME 0.209

Same issue as Hidden Level 26. The TripPads are firing one speed faster than they are when playing in the Editor. 

The pairs of TripPads92/97 and TripPads93/98 fire too fast for the player to jump the second slower one as designed. Level breaker for now. Can't progress forward from this point.

This may again be happening because the outerspace level (4th base w/two red lines) is playing before you land and get to got through this maze.

If not I can always dial these back one speed setting to compensate for the speed up issues when playing from level 1. Let me know.

**Comment by jessaskey** [comment]
- Hoping that removal of Adaptive Difficulty will fix this, will link it to release 0.59 and then get feedback from Jerky.

**Comment by jessaskey** [comment]
Going to track this under #150
