### ISSUE TITLE
Level 20 - Missing Level 20 text on HUD and skips breakoout game

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#141]
0.58 romset
HBMAME 0.209

Playing from Level 1>20 + all secret levels except for L28 (skipped due to trip-pad speedup issue).

After finishing level 19 the game hops right into the outerspace battle skipping the breakout game at the HUD screen. The text on the lower left side for "level 20" is also missing.

**Comment by jessaskey** [comment]
I think this was a save file issue from around the time this was submitted... going to mark as closed for now.

**Comment by jessaskey** [comment]
Same as the other issue, Im not able to duplicated this one as I can't play straight up to Level 20, so if you can send me a MAME savestate for this when it happens (pause on tact when it is missing) and I can try to dissect it. thank you!
