### ISSUE TITLE
Level 21 - Missing Text "Level 21" at HUD screen

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#142]
0.58 romset
HBMAME 0.209

Playing from level 1>21 + secret levels except for Level 28 (trippad speed up issue).

The "Level 21" text on the lower right side of the HUD is missing. Yesterday this level also jumped past the breakout game like the Level 20 bug I noted earlier (but Level 20 was okay that time letting me play the breakout game). Today it skipped the breakout game at Level 19 but did not at 20. Both levels missing the "Level #" text though.

**Comment by jessaskey** [comment]
Not able to duplicate this as of 0.67 so Im going to close it for now.

**Comment by jessaskey** [comment]
Jerky, Im going to close this so it disappears from the issue list, but if you see it again from ROM 0.75 onwards, submit it again and include a MAME save state so I can investigate. I have a hard time playing straight through to level 21 and if I just start here or warp to it, everything seems fine. I think you might be finding a bug that is from the previous level perhaps but I just can't find it. thank you.
