### ISSUE TITLE
Level 22 - TripPads sped up

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#143]
0.58 romset
0.209 HBAME

Playing from level 1>22 + all secret levels expect for L28 (also trippad speed issue).

Like a few other levels the TripPads seem to be sped up by adaptive difficulty somehow. If you can't figure out why I have been editing a new .mhc that sets the TripPad speeds back one level to compensate for this issue.

You can just barely squeak by the lower hallway's trippad shots at this higher speed value now (that you don't see sped up in the editor or going right to this level via demo mode).

**Comment by jessaskey** [comment]
- Hoping that removal of Adaptive Difficulty will fix this, will link it to release 0.59 and then get feedback from Jerky.

**Comment by jessaskey** [comment]
Going to track this under #150
