### ISSUE TITLE
Level 22 - Oxygen consumption sped up...not enough to finish Level 23+ now

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#144]
0.58 romset
0.209 HBMAME

Playing from level 1>22 + first three secret levels (Skipped L28 due to trippad speed issues).

The oxygen consumption is sped up on this level leaving you with barley enough to finish this maze and not enough to get through the next one (L23).

I checked against playback vids I made of this level previously and made several seperate runs from level 1 to test it again.

I can up the o2 levels to compensate in the current .mhc I am working on if these speed issues cannot be figured out. Could be related to the extra outerspace level playing before all secret levels? (pushing the AD higher than it should be for other later levels like this...but does not affect every level somehow).

++++ing o2 for now....

**Comment by jessaskey** [comment]
- Hoping that removal of Adaptive Difficulty will fix this, will link it to release 0.59 and then get feedback from Jerky.

**Comment by jessaskey** [comment]
Going to track this under #150 since it is related to AD.
