### ISSUE TITLE
Level 15 - One TripPad sped up...others okay?

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#145]
0.58 romset
HBMAME 0.209

Playing from Level 1>15 + secret levels up to this point.

TripPad53 is firing one speed faster than seen in the editor but the other ones don't seem to be affected (51+52).

This could be related to the extra outerspace level playing b4 secret levels (at a high level of difficulty)?

**Comment by jessaskey** [comment]
- Hoping that removal of Adaptive Difficulty will fix this, will link it to release 0.59 and then get feedback from Jerky.

**Comment by jessaskey** [comment]
Going to track this under #150
