### ISSUE TITLE
Secret Levels Too Quiet - Make Final Maze Background Sound

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#148]
Someone also just mentioned this in a comment for one of my Secret Level YouTube videos. 

Since there are none of the usual things that make sound effects in other levels on these ones maybe some sort of interesting background sound(s) would help? Something creepy like the throbbing reactor sound or something similar to it?

How about a sinister sound effect for the Maxoids as they move too? I know ours doesn't have spinning blades but...

**Comment by jessaskey** [comment]
Okay, Im going to turn this ticket into a 'make background music' which will just be a single channel bass line... I should be able to make it slowly increase in pitch as the player gets through each section as well as a tension builder perhaps. 

I will make a separate issue for the Max Robot sound (which is a great idea too)....
