### ISSUE TITLE
Create sound effect for Maxoid

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#149]
Max clearly needs a sound.. maybe something that pulses to the same timing as his eye pulsing.. any other ideas?

**Comment by jerkyspace** [comment]
Well even though he does not have whirling blade arms like his inspirational brother...it's a great sound effect or something like that. Not sure how you would manage it for multiple maxoids though. Sending you an email example...

**Comment by jessaskey** [comment]
Okay... 0.59 will have this done... here is how it works currently. Once Max is activated, he will say 'Activated' and the background sound will start... it will increase in both volume and pitch as he gets closer to Rex. If there are multiple Max robots, the closest Max robot will drive the sound configuration (since there is only 1 sound, I can't layer them with multiple Max robots because it would take up to 6 sound channels and that is too much for right now). If a Max robot touches Rex, Rex dies and Max will "laugh" at him.
