### ISSUE TITLE
New game will end up playing the VAXX space station for 1st level.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#167]
Start a game and get into the 1 Space Station. Kill off all your lives except the last. Allow your last man to die by running out of Oxygen. Immediately start another game. 

Note that the Scanner page appears to be drawing 2 different versions, the score is all whacked out, and when you launch to battle the space station you're at the home world.

**Comment by jessaskey** [comment]
Okay, I found this issue... looks like the startlevel variable was going to 0xFF which was not making the game initialization code very happy since it was -1.

**Comment by bakerhillpins** [comment]
This is fixed in the latest ROMs you sent.. mhavocpex7_079blr
