### ISSUE TITLE
Loosing your last life in the space maze results in a weird space maze during the continue screen.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#168]
Play up to level 3 where your attack on the space station is via the maze. Die inside the maze and the attract mode afterward has a janked up space maze draw on it.

![image](https://user-images.githubusercontent.com/5980709/161393796-34063e8c-f702-4a81-a002-b19f5c0e9a79.png)

**Comment by jessaskey** [comment]
So, this is weird as I just can't replicate this in MAME at all. Is this something that you can do consistently?

**Comment by jessaskey** [comment]
Okay, looks like I had some memory overlap between the space maze and some of the vars used in switching players and transitioning between major game sections. I moved the space maze base RAM location and things seem to be okay now.

**Comment by bakerhillpins** [comment]
This is fixed in the latest ROMs you sent.. mhavocpex7_079blr

**Comment by jessaskey** [comment]
I just saw this one again in v0.80 again on the space maze after game level out graphic. I will go see what the overlap is between the high score table and the space maze, that must be the issue.

**Comment by jessaskey** [comment]
I needed to shift the fireworks object variables into a set of Maze vars that were not used even in the 'after game' level. I ended up also needing to not use some of the temp variables that were used in the space maze and other phases of the game because the fireworks were messing up those states and causing weird behavior.

**Comment by bakerhillpins** [comment]
Ah, I bet that's why I didn't see this when I tried it again. Because I don't actually get a top 3 high score much since I've basically filled them up with scores which require me to get past the first 6-8 levels.
