### ISSUE TITLE
Warps codes resetting on each GAMMA reset

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#171]
It appears that the random warp codes are being reset and rerandomized on every gamma reset, including in the EEROM... why?

**Comment by jessaskey** [comment]
This was a bug in the gamma reset code. The intent was to initialize any warps that were undefined (-1) because if a new EEROM was ever inserted or if MAME was run fresh, then the values were invalid. The code was simply doing all warps regardless of the current warp value.

**Comment by bakerhillpins** [comment]
I noticed this and thought that was on purpose so that the player would have to figure them out each time the game lost power.  Which was incredibly hard but anyway. I'm glad you are planning on changing this.
