### ISSUE TITLE
Roller flashes at 2x rate when coined up.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#175]
Don't know if it's intentional or not but in free play/when coined up the Roller flashes at 2x the Production speed.   I personally prefer the OEM setup. 

If it matters, when in self test, it flashes at the OEM speed.

**Comment by jessaskey** [comment]
I was wondering if I was going to mess up the timing on this one... I don't have a flash indicator on MAME and on my Alpha One proto, it has a solid black roller and no wiring for the flasher bulb. :-)   I will halve it now and you can check it out in the next ROMset I send ya!

**Comment by bakerhillpins** [comment]
This is now flashing at 4x on the v0.80 ROMs.

**Comment by jessaskey** [comment]
Failed... created #185 in the v0.81 release
