### ISSUE TITLE
End of game continue mode not needed for Demo Mode

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#176]
When playing in Demo Mode, at the end of the game it puts up the Continue/Buy In screen. This screen is a variation of the Demo Screen but it only lets you start up to level N-1 so it's limiting/confusing. For the first couple games I sat there letting it timeout because I wanted to start at a higher level but then I realized that if I hit the start button (because I'm in free play) It would immediately change to the standard Demo Screen with all levels as an option and let me pick. I wish I knew that earlier, LOL.

Can we change the code to skip the continue screen when in Demo Mode?  Mostly because it was confusing and I sat there waiting until I accidentally hit a start button and realized I could skip it. Your scores don't get saved to the High Score table so continuing doesn't really "buy" you anything to continue and most folks probably want to go back to the level they just died on anyway.

**Comment by jessaskey** [comment]
Okay, I think I have this fixed now. In testing for v0.80.
