### ISSUE TITLE
Change position of Tesseract on level 10

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#177]
The Tesseract that we use to hint of their existence on level 10 isn't seen when dropping into the maze.  IIRC the idea here was to make it close enough to the player dropping into the maze so that it would just fade in and out of existence, thus hinting at hidden things in the game. On my game with what I'll call "decent" color adjustment I don't actually see it fade in unless I move Rex to the left when he's falling into the level.  We should probably move the Tesseract to the right to adjust for this? Off the cuff I was thinking about 1/3 of the current distance away from the entry of the maze.

**Comment by bakerhillpins** [comment]
The Tesseract that we use to hint of their existence on level 10 isn't seen when dropping into the maze.  IIRC the idea here was to make it close enough to the player dropping into the maze so that it would just fade in and out of existence, thus hinting at hidden things in the game. On my game with what I'll call "decent" color adjustment I don't actually see it fade in unless I move Rex to the left when he's falling into the level.  We should probably move the Tesseract to the right to adjust for this? Off the cuff I was thinking about 1/3 of the current distance away from the entry of the maze.

**Comment by jessaskey** [comment]
Okay, this is fixed... I nudged the tesser right over to the left side of the wall now. I have a new set of Editor ROM images that I can check into the mhedit project too... but to be honest, Im not sure how to make new branches anymore in that project. You might need to help me (or I can send you a .zip of the template ROM images if you want). Moving this one to testing now. It will certainly help if the player glides rex over to the left as he falls into the maze but hopefully even on your monitor now the tesser is faintly visible for a teaser.

**Comment by bakerhillpins** [comment]
> but to be honest, Im not sure how to make new branches anymore in that project.

Nothing has changed about how you check in any ROM updates or make releases. Do it how you have in the past. I'm off on some branch making a complete mess working through a handful of the issues that were effectively blocking me before I make an investment in changing everything else around it.
