### ISSUE TITLE
Space Station explostion in wrong place on screen

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#180]
It seems like after Style C (level 3) mazes, that after leaving the maze, that the space explosion could be rendered wrong. I have seen it down in the corner, or sometimes with just like quadruple explosions.... not sure how consistent this is tho.

**Comment by bakerhillpins** [comment]
OK, I think I'm seeing what you're talking about here,  It might also only be for certain levels as I could swear it looks OK on some of them.

**Comment by jessaskey** [comment]
Okay, I found this issue very specifically, should be good to go now in this release.
