### ISSUE TITLE
Self Test Settings not staying put/changing

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#181]
From Bryan: For some reason Free Play/Coin settings don't allow you to change them away from the DIP settings. And once you've made a choice in Self Test it will not allow you to change even if you actually change the DIP setting. The only way to get it to move is to select the reset to DIP and then it will follow the new board setting.

From Jess: I was able to see this by just trying to save the coin settings to 1 Coin 1 Play and after applying, it instantly snaps back to Free Play. Something going on with the setting or decoding of the values saved in memory.

**Comment by bakerhillpins** [comment]
Loaded up the new .80 ROMs and noted that several values are incorrect, at least according to the manual. I have not loaded up the OEM ROMs to validate that it reads it differently.

I've got DIP settings for Med Diff, 3 lives per player, and Adaptive off.  Self test screen says (and game plays) 4 lives per player and Easy Diff.  Adaptive is ignored.  (Easy Diff is new for V 0.80 ROMs. The .79 build had Med for these settings)

DIPs are 1/2 ON, 3-7 OFF, 8 ON (to turn off Adaptive on OEM)

**Comment by bakerhillpins** [comment]
Loaded up the OEM ROMs and they read the DIPs as I'd expect based upon the switch settings.

**Comment by jessaskey** [comment]
Just to clarify... if you put in HavocPE ROM's and your NVRAM already has data from PE, it won't reflect what is on the DIPS. The DIPS are only used if you go into SelfTest and select the 'RESET ALL TO DIPS'.

Also, the DIPS are slightly different on PE... for for all intent purposes, you really don't need to use them since you can change the game settings in self test. 

```
;*************************************************************
; Option Switches Master Reference from GAMMA
;
; Game Pricing @8S - Default off OFF
; MSB			     LSB
; 1   2   3   4   5   6   7   8 
;---------------------------------
; 			  Off Off	   1 Coin 1 Play (Default)
; 			  On  On	   1 Coin 2 Plays
; 			  On  Off	   2 Coins 1 Play
; 			  Off On	   Free Play
;
; Game Settings @12/13S - Default all OFF
; MSB			     LSB
; 1   2   3   4   5   6   7   8 
;---------------------------------
; Off Off				3 Lives (Default)
; On  On				4 Lives
; On  Off				5 Lives 
; Off On				6 Lives 
; 	  On  On 		        Hard Difficulty
;         Off Off			Medium Diffiulty (Default)
;	  Off On		        Easy Difficulty
;         On  Off			DEMO Mode
;                 On  On 		Bonus @ 50,000
;                 Off Off		Bonus @ 100,000 (Default)
;                 Off On		Bonus @ 200,000
;                 On  Off		No Bonus
;   			   On	        Silent Attract Mode
;                          Off 	        Sound in Attract Mode (Default)
;                              On       Roller Multiplier x2
;                              Off      Roller Multiplier x1 (Default)
;       
;*******************************************************************
```

There is still a bug here tho... because the behavior Im seeing is that lets say I change it from to 'Free Play' and then save it... well, it instantly pops back to '1 Coin 2 Plays'.... which is clearly incorrect.

**Comment by bakerhillpins** [comment]
Gotcha.  
One of the thing's that's confusing here (thus is generating comments from me) is that the OEM ROMs have the # of lives per game setting tied to the Game Pricing option. For Example the OEM setup has the 3 lives per player on Free Play, and 4 per player on 1 coin per 1 play in the 2nd row in the pic below.  

![image](https://user-images.githubusercontent.com/5980709/167627283-584b15e7-329d-46b3-9218-2c2518bece7f.png)

It appears that you've removed that in PE, so for instance, I'm using Free Play, and when I switch back and forth I noted I'd go from 3 to 4 lives per game. This is FAR from a big deal and I'm happy with choosing the # of lives based off of the 1 coin per play table.  I'm just getting brain scrambled switching back and forth and keeping this all straight. 

> There is still a bug here tho... because the behavior Im seeing is that lets say I change it from to 'Free Play' and then save it... well, it instantly pops back to '1 Coin 2 Plays'.... which is clearly incorrect.

Yea, in the end it appears this is the only actual bug, the rest is me being confused.

**Comment by jessaskey** [comment]
Yep, I got rid of that and also eliminated the 2 players per game setting as it was silly. Plus, I needed ROM space in non paged ROM. The whole 2-Coin minimum is also gone.

**Comment by jessaskey** [comment]
Okay, I somewhat gutted this and verfied that it all works in MAME now correctly. Will test in ROM's after release.

**Comment by bakerhillpins** [comment]
Ok, this appears to work now, selections change and stick, but when I "Reset To Dips" I end up with 2x the roller speed rather than 1x which is what I'd expect.

**Comment by jessaskey** [comment]
I will investigate this new issue and pin this to the v0.82 milestone.

**Comment by jessaskey** [comment]
So, can you make sure that your switch @ 13/14S switch #8 is in the OFF position? That is the default and should result in a roller multiplier of 1X. That switch position was the old Adaptive difficulty switch and if you had Adaptive difficulty turned OFF, then the roller would be showing as X2 on 'reset from dips'

**Comment by bakerhillpins** [comment]
OOF, that's my bad.. I've got Adaptive Difficulty set to OFF on the OEM game which apparently translates to 2x roller speed. That must have been an issue that I didn't notice previously because it took me by surprise when I upgraded to test this.

Hrm... I'm being lazy here and thinking about this from a "what's the most common DIP settings" to make transition back and forth less painful switch wise.  On the other hand, moving to PE you just set them in self test (not on the board) so I guess it shouldn't matter. 

Always thought it was weird why you didn't override the Bonus Coin switches..  Who ever used those????

Note docs have the switch location wrong (well the ones you pasted in above anyway)
![image](https://user-images.githubusercontent.com/5980709/170023993-87e34d6c-7cd8-4809-86a6-cba48bcd739b.png)

**Comment by jessaskey** [comment]
Yeah, using the bonus coin switches would be a good idea. I used the other DIP because those are 'game settings' and the other DIP are 'coin settings' so I stayed in that frame of mind, but in hindsight, it would have been better to put this setting over on the coin DIP to avoid confusion.
