### ISSUE TITLE
2 player game - 2nd player's turn the controls don't do anything on Dedicated cab

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#182]
If you play a 2 player game the 2nd player can't play because the Roller doesn't move the ship and the fire/shield buttons don't work. I'm betting something is compiling in Cocktail mode.

On that note, there is no DIP switch or Self Test option for Cocktail mode. Not sure how you were thinking of implementing that.

**Comment by jessaskey** [comment]
So the cocktail mode on the later Atari games (and actually Major Havoc specifically) is implemented by the 'Cabinet' input on the edge connector. Reasoning behind this is that I think Atari didn't want operators to have to deal with flipping DIPS when swapping out PCBs... so if you look on the Havoc Alpha Memory Map, you can see on the inputs ($1200) bit D7 is the cabinet input. When not connected, it should be pulled up via R11 to a Logic 1... this would be the 'default' of an UPRIGHT. I will check this on my cabinet tomorrow as I clearly have this flippety flopped in code. :-)   MAME didn't implement this input so I never tested it.

**Comment by bakerhillpins** [comment]
> So the cocktail mode on the later Atari games (and actually Major Havoc specifically) is implemented by the 'Cabinet' input on the edge connector.

Ah, yes... that's correct. I knew I wasn't remembering something when I was reviewing this in my head.

**Comment by jessaskey** [comment]
Okay, found the issue on this one... moving to testing for the v0.81 release.

**Comment by bakerhillpins** [comment]
This is fixed on 0.81 for the upright game. I don't have a way to test cocktail mode though. Well I could jump some pins to GND. Might try that later.

**Comment by jessaskey** [comment]
I wouldn't spend time trying to flip this.. it will probably become a timesuck because you will also need to bridge the buttons over to the 2P inputs AND wire in an opto to the 2P LETA inputs. I am fairly certain that this will work and someone that actually has a cocktail setup (not factory) can spend the time testing and reporting any issues. :-)
