### ISSUE TITLE
Truncate the Alphnumerics on the crosshatch screen in Self Test

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#186]
I noticed that the original havoc during the crosshatch screen, ran the alphanumerics off the edge of the screen. Given that I have now added about 20 more characters, it is probably not very healthy for the monitor to draw ALL those characters. We should stop the alpha characters after the letter Z to keep text tested, but not excessive.

**Comment by jessaskey** [comment]
Okay, this is done... Unfortunate side effect of this is that all the Vector ROM's will need to be reburned for v0.81

**Comment by bakerhillpins** [comment]
LOL, I've been re-burning everything anyway.

**Comment by bakerhillpins** [comment]
This is truncated now.
