### ISSUE TITLE
Max Robot colors seem extreme 

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#187]
So I played Level 25 in demo mode, and the max robot at the center of the maze starts dormant.  On my monitor he's barely visible in this state. My red levels seem fine in the game otherwise. 

Then when you wake him up, it's like he's a neon sign.  I think these 2 states need adjusted a bit inward so the contrast between the 2 isn't so exaggerated. I'll add pics in a bit.

V0.81 roms

**Comment by bakerhillpins** [comment]
Images
Deactivated:

![image](https://user-images.githubusercontent.com/5980709/169419014-4bc372da-d5f7-47c5-92e8-d4b73debef65.png)

Activated: (Not so great, tried to move away while snapping)

![image](https://user-images.githubusercontent.com/5980709/169419053-79086683-62da-45f2-97eb-823d85ea1588.png)

**Comment by jessaskey** [comment]
The 'dim' state for the Max Robot was set to intensity ($60)... I moved this up to $80.

However, the weird thing is that the 'bright' state of the Max robot is intensity $E0 BUT I looked at the red sparkoids routine and those are drawing with an intensity of $F0 so those are/should be the brightest RED2 color, even brighter than the Max robot. Im curious what your Trip Pad pyroids look like in comparison?

**Comment by bakerhillpins** [comment]
Weird, the TripPadPyroids don't appear to be as "neon". I'll grab a few more pics of the enemies in question as well as take a pic of the self test screens that show intensity. (Both of them)

**Comment by jessaskey** [comment]
So the only way that a Max could be substantially brighter then is that they are being drawn more frequently than the other objects... I might have a looping bug that is redrawing the max body more than once... this is something that from a MAME standpoint, I wouldn't be able to see.

**Comment by jessaskey** [comment]
Okay, updated to dim of $A0 and Bright $E0... both are normal RED now instead of RED2 (intense RED)
