### ISSUE TITLE
Max Robot sounds are not turned off at end of turn/game

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#188]
Play level 25. Activate Max Robot and you will hear the sound associated with him. If you are killed while that sound is active it will not be turned off. 

If you restart the level, it will be turned off when you drop into the level.
If your last man dies while that sound is active it remains on in attract mode. Forever, as far as I can tell. I went into self test to make it stop.

**Comment by jessaskey** [comment]
Okay, I think this one is good... set to status = testing
