### ISSUE TITLE
Adjust Long Range scanner when doing tesseract level

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#191]
When the player lands in the tact scan for a 'hidden' tesseract level. The Level # should not be shown (because they are in a way 'levelless'.... so that should be hidden. Also, to go along with that, the normal left side animation of the ship should be hidden too because that shows a linear progression from start to end, but the tesseract levels are supposed to be in different time and place from the linear progression, so that should go away too.

**Comment by jessaskey** [comment]
What Im going to do for this is to hide the 'Level XX' part of the text.. and then the Long Range Scanner will still have the planet and vax cube ending but will show a pulsing 'question mark' in the normal left box. This should work decently enough.

**Comment by bakerhillpins** [comment]
Seems reasonable to me. Glad I grabbed a video of it for you. Lots more info in there I didn't notice.
