### ISSUE TITLE
Tactical Scanner timeout seems short

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#192]
The Tact Scan timeout seems really short if you don't touch a button to start the breakout game. I'm counting basically 2ish, maybe 3 seconds before exiting the screen. I've always found that faster than comfortable. I recall the OEM game being quick as well. BITD it was probably to keep game play time within a specific range but now I think maybe we could add a little here?  I think this matters more when the Warp Code is published at the top of the screen. It feels rushed to read and continue playing breakout but maybe we don't care either?

Moving the roller doesn't change the delay. However, if I push the button it seems to add 4ish more second to the timeout.  Possibly because it seems to delay 4ish seconds after you loose the ball and that's added to the end of the 1st timeout?

**Comment by jessaskey** [comment]
Im going to leave this one as is... I *did* however somewhat shorten the tact scan timer if there is a warp message being displayed.. it was at like 12 seconds, I changed it to more like 9 seconds now.

**Comment by bakerhillpins** [comment]
So I just commented on #202 with regard to this.  I don't think the timing code with respect to these is accurate anymore.
