### ISSUE TITLE
Screen goes black when Maxbot kills you

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#197]
This doesn't happen all the time but seems to happen MOST times.

Let max kill you in a maze and when he first turns you into a flashing skeleton the screen goes blank for like 1 second. Then it comes back to normal. Doesn't seem to affect any other things.

0.85, PE mazes, playing the first XX (token) level and level 21. 

I have a video but as it's relatively common it shouldn't be hard to reproduce.

**Comment by jessaskey** [comment]
Okay, I found this issue and it should be fixed in ROMset v0.86 forward.

**Comment by bakerhillpins** [comment]
0.86 PE - I just had this occur on 2nd XX level.  I've not been able to repeat it.  I activated the Maxbot on the left hand side of the maze by landing close to him and spinning out away from him in one quick fast motion.

**Comment by jessaskey** [comment]
I *think* this is fixed but I will leave this open in case it pops up again.
