### ISSUE TITLE
Clock doesn't slow down time.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#201]
0.85 PE  Level 13 Demo mode play

When I activate the clock on Level 13 time does not appear to slow down, nor does the countdown timer when you activate the reactoid.

**Comment by jessaskey** [comment]
Does the clock do it's spinning animation?

**Comment by bakerhillpins** [comment]
Here's a video I took.


https://user-images.githubusercontent.com/5980709/178976425-d04ad125-f913-4e15-a593-e5a1e5c447c6.MOV

**Comment by jessaskey** [comment]
So... Clock does not affect Ion Cannon shots OR the Reactor timer (which it *is* weird that it doesnt' affect the reactor timer, but it doesn't). You might ask, why is the clock on this level then? Well, it does affect the Trip Pad pyroids, so it *does* do something, just not much on this level. Really, in summary, the only thing that the clock affects are Pyroids, Perkoids and Perkoid shots.

**Comment by bakerhillpins** [comment]
I'm getting old and CRS.  I guess that was the main issue, I sorta figured if the clock was there it would have some affect but that must only be on the TE setup.

Sorry for the runaround.

**Comment by bakerhillpins** [comment]
Isn't there a Not a Problem option?  We should probably close it regardless as it was my mistake.
