### ISSUE TITLE
Death by maxbot on last XX level plays MH theme

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#206]
0.85 PE

If I play the last PE XX level and get killed by the Maxbot in the center of the maze the game plays the MH theme?? I don't have any of the audio hardware so not sure if that's the reason or not.

I can add a video if necessary.  You get the booties, travel down the left hand side, across the bottom, and up the center. I typically get him to chase me down a bit and die and I get theme music.

**Comment by jessaskey** [comment]
Which theme.... the "chord.. whoop, whoop, whoop... chord... whoop, whoop whoop"?  And it is always the same one for you right?

**Comment by bakerhillpins** [comment]
Lol. I don’t remember which one. Yes same one each time. I’ll go get a video in a few.

**Comment by bakerhillpins** [comment]
https://user-images.githubusercontent.com/5980709/179651804-a3e2a496-6d0a-4d4c-bf8a-28110980db07.mp4
