### ISSUE TITLE
Ship/Score seem to temporarily disappear on transition into tact scan

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#207]
In the video below.... the ship and score disappear during the transition... this does NOT happen in MAME tho.

**Comment by jessaskey** [comment]
https://user-images.githubusercontent.com/3683098/179641295-1c1e384d-3c63-4054-9ca5-3744ca556be7.mp4

**Comment by bakerhillpins** [comment]
This appears to be fixed in 0.86 PE.
