### ISSUE TITLE
Level 9 is missing Fishoids

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#210]
0.86 PE

Level 9 is missing 2 Fishoids?  Happens in Demo Mode or play through.

![image](https://user-images.githubusercontent.com/5980709/180081725-ae5f8259-25fd-40cd-b6dc-6077bfaf6b93.png)

**Comment by jessaskey** [comment]
Okay, this is fixed.... a true fat finger bug!

**Comment by bakerhillpins** [comment]
This is fixed in 0.87 PE
