### ISSUE TITLE
Breakout paddle keeps changing size.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#212]
0.87 PE

So I didn't realize there was a 2nd breakout game and it caught me off guard. I will say that the time to complete it goes WAY faster with 2 balls and a little luck.

I did notice that the paddle keeps changing from big to small. I couldn't quite make out what was causing it. It gets smaller as expected when you hit the top of the "screen".  However, it appears that either hitting a lower level block or maybe loosing one of the balls causes it to get bigger again. It could be that hitting the top of the screen is toggling it.  Wish I had a video...

I'm kinda inclined to consider this a "feature" that makes it harder. But we'd need to understand what's causing the toggle and make sure it's not just stupid.

**Comment by jessaskey** [comment]
I believe that this is now fixed!
