### ISSUE TITLE
Tesseract is lost from High Score that drops out of the top 3.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#217]
If High Score number three has a Tesseract and a new High Score 1 to 3 is achieved, It bumps the number 3 score down to 4 as expected. However, the score that shifted to the number 4 spot will no longer displays the Tesseracts that it had next to it. 

If I achieve a High Score 4-10 and get a Tesseract during play it is placed next to that score so I'd expect it to be bumped down.

**Comment by jessaskey** [comment]
Okay, this should be fixed now. Tested pretty extensively and was way more complicated than it had to be. :-)

**Comment by bakerhillpins** [comment]
This is fixed in 1.01 beta
