### ISSUE TITLE
Demo Mode level 10 lists Warp Code.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#220]
I know that Demo Mode does some wonky stuff but I noticed that when starting on Level 10 it presents the ---Intercepted Message--- text for the Green Warp code 824.  This isn't the correct place for that message. Level 9 correctly presents the Yellow Warp. No other level that I've tried in Demo Mode gives that warp code info incorrectly, just level 10.

![image](https://user-images.githubusercontent.com/5980709/207643509-3c8f8264-8f8b-4773-a01a-5564efe2d6a3.png)

**Comment by jessaskey** [comment]
Okay, I reviewed this and it was all set up weird. I looked at the original source and it looks like I was actually showing the warp numbers AT the level the warp took you too, which was wrong... you need to get to the level after the target warp level.  So to see Red Warp (which takes you to level 4), you need to make it to Level 5.  Using that logic, this is how things map out...

Does this make sense?

;At what level is the warp code shown to the player        
?teltab 
        .db -1  ;Level 1
        .db -1  ;Level 2
        .db -1  ;Level 3
        .db -1  ;Level 4 
        .db 00  ;Level 5 = Red
        .db -1  ;Level 6
        .db -1  ;Level 7
        .db -1  ;Level 8
        .db -1  ;Level 9
        .db 01  ;Level 10 = Yellow
        .db 02  ;Level 11 = Green
        .db -1  ;Level 12
        .db -1  ;Level 13
        .db 03  ;Level 14 = Aqua
        .db -1  ;Level 15
        .db -1  ;Level 16  
        .db -1  ;Level 17
        .db 04  ;Level 18 = Blue
        .db -1  ;Level 19
        .db 05  ;Level 20 = Purple 
        .db -1  ;Level 21 = Final Maze
        .db -1  ;Level 22 = Final Maze 
        .db -1  ;Level 23 = Final Maze
        .db -1  ;Level 24 = Final Maze
        .db -1  ;Level 25 = Hidden Level no hints
	.db -1  ;Level 26 = Hidden Level no hints
	.db -1  ;Level 27 = Hidden Level no hints
	.db -1  ;Level 28 = Hidden Level no hints
        ;We won't show the final warp code until after 
        ;the homeworld is completed this is done in the 
        ;winner sequence
        ; 06  ;Homeworld = Pink

**Comment by MajorHavoc** [comment]
From the peanut gallery: Actually, you got the warp code when you REACHED a level. The code allows you to start there because you made it there. It’s not wrong, it was designed that way. If you reached level 4 (for example) then you earned the code that would take you to the start of level 4. Otherwise you push people back one level when they warp.  I don’t like that. -Owen-Sent from my iPhoneOn Dec 28, 2022, at 10:17 PM

**Comment by jessaskey** [comment]
Hola Owen... what you are saying is exactly what I was thinking too from my memory... get to Level 4 Tact Scan and it should show you the Red Warp code which takes you to level 4 if entered on Level 1,2 or 3. But looking at the code AND playing through your v3 ROM's... the Level 4 warp code is shown on completion of Level 4 during the Level 5 tactical scanner. This is actually very similar to the way that Tempest is, you have to attain the Level+1 to get the award and just like you mention... if you warp or continue and don't finish a level, then you essentially start losing the ability to stay on the same level to continue. 

I agree with you in that if you reach a level, then you should be given the warp to get to that level again. The only thing I *will* have to check is that lets say you enter the warp code and land on Level 4, then obviously you don't want the warp code showing up again at the top of the tact scan... it should just be happily allowing you to enter the Yellow warp. You had code that dealt with this before but I will need to tweak it.

Bad screenshot from MAME below.... v3 Atari ROMs.

![0000](https://user-images.githubusercontent.com/3683098/209979054-367af319-11b1-4032-b579-38911c4eec04.png)

**Comment by jessaskey** [comment]
@bakerhillpins ... I fixed the completely jacked message of showing the Level 10 Green Warp ON Level 10 now (v1.01)... TBD on if things get shifted all around the way Owen and I were discussing above.
