### ISSUE TITLE
Score display never disappears after game

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#221]
So I honestly don't know how this works in the OEM ROMs, but I noticed that when you power up the game there is no score display in the upper left hand corner (or right for 2plr).  This makes sense as no one has played yet.  If you play a game however, the score display is effectively permanent in that it's never taken down after that point.  It's ALWAYS displayed during the attract mode from this point forward and of course during game play. I'd assume that if I played a 2plr game then both scores would be displayed until the next 1plr game.

So my thinking is we might want to change this to avoid burning a score into a screen? I'd say we definitely want to if the OEM code turns it off but I'm betting you didn't mess with this. Just about every game in existence burns a blob of digits on the screen where the score is displayed so it's not exactly unheard of or uncommon. We could make arguments that this is bad/ok for both home/arcade play.

**Comment by jessaskey** [comment]
Yeah, I hear you on this one... it is a slippery slope... I will elucidate below....

On the NOT THERE and then THERE, you are correct. I took off the score and the popup purple award points during attract just to make things as smooth as possible looking on real hardware. I actually didn't realize that it came back, but to your point, that sorta makes sense that it is there after someone plays... it allows players to see a score they can try and beat.

On the screen burnin, I have thought about this quite a bit an even thought about putting in weird random vector before any 'static vectors' that show up in the same location regularly... BUT, the downside is that it would need to be drawn after EVERY vcenter and it would add up to a good dozen extra vectors sometimes... and THAT is the one place that the real hardware starts to slow down. 

I after watching my Tempest do this insanely bright attract mode in the exact same position every 45 seconds, I thought there might be a better way to deal with this NOT inside the software. More to come on that. 

So, Im going to mark this as "not gonna fix' for now at least!
