### ISSUE TITLE
Demo mode credits required issue

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#224]
When in demo mode, credits are initially set to 2, but when starting a new game, the credits decrease. When they hit 0, then you can't start a new game in demo mode until you add more credits.

**Comment by bakerhillpins** [comment]
I just realized that the reason I don't see this is I'm setup for free play. Maybe the solution is to simply force Free Play in demo mode?

**Comment by jessaskey** [comment]
Yeah, it is a little weird in there around this... I just added a check for both Free Play AND DEMO to force 2 credits to always be on the game.
