### ISSUE TITLE
Switches not registering in test mode

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#226]
With the changes to Self Test the screens aren't exactly the same as OEM but I'm inferring that on the Input/output screen I should be able to press the Fire/Shield/coin1/coin2/Aux/ etc and see a bit flip on the screen. This doesn't happen.  The switches obviously work in test as they perform actions on other screens.

**Comment by jessaskey** [comment]
Okay, this is fixed.... it actually wasn't broken... the display just wasn't showing the GAMMA inputs yet.... I added them.. If I get time in this release, I will add a final bottom row for the Alpha Switch inputs (Coins, Self Test, etc)

![image](https://user-images.githubusercontent.com/3683098/210157167-b3d7fb4b-e03f-4602-8aa4-3737c75f1ebd.png)

**Comment by jessaskey** [comment]
Okay, I added the two mux values of the Alpha Inputs now too... this should now be a solid I/O screen for assistance in troubleshooting!  

![image](https://user-images.githubusercontent.com/3683098/210182703-5c7218c9-2609-42b4-9287-338d500a09d4.png)

**Comment by jessaskey** [comment]
Okay, I added the Alpha inputs now in both MUX positions (Player 1 signal)... this should be a solid troubleshooting screen now!

![image](https://user-images.githubusercontent.com/3683098/210182780-0333dfac-8761-4b92-84b0-90d6c4ca2e7f.png)

**Comment by jessaskey** [comment]
Someday I should make a manual for this I suppose!  NOTE FOR ABOVE:  D0 is on the left and D7 on the right, seems backwards to me because I look at code all day and 6502 is little endian!

**Comment by jessaskey** [comment]
Also, I updated and submitted a pull request to the main HBMAME repository to fix some weird stuff with the coin inputs that have been there since the original mhavoc driver. This separates the coin switches properly and they register properly here in this test now.. Yay!
