### ISSUE TITLE
Max keeps making hit sound after first hit.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#227]
If you hit a Maxbot with a Trip Pyroid he makes a grunting sound.  However, rather than making just one sound each time he's hit he continues to grunt until he's killed.

**Comment by jessaskey** [comment]
So like the grunting is continuous after the first hit until he is killed... 'ughhh'...'uggggh'... 'ugggh'...'ugggh'...'ugggh'... etc even when he is not getting hit? Also, there are two different sounds for Max being hit (random)... Im wondering if it is random or the same one over and over ad infinitum?

**Comment by bakerhillpins** [comment]
I'll try to get a video this morning. I don't believe it's the same sound repeating tho. 
[edit - I know this is late but I'll put the video up anyway]


https://user-images.githubusercontent.com/5980709/211038652-9394e064-416c-4a28-8365-971c08ad3e4c.mp4

**Comment by jessaskey** [comment]
Okay, that is very helpful to know because that means it is on the Alpha side of the code and not in the Gamma code! :-)

**Comment by jessaskey** [comment]
Okay, this oddly was an issue all the way up in the ADPCM speech ROM on the daughtercard. Not an Alpha OR Gamma issue. Weird this hasn't come up yet, but it appears to be the only thing weird on the Speech ROM.
