### ISSUE TITLE
Text positioning issues on Gamma CPU test page

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#229]
The white text phrases shift left and right as you cycle through them (Reset scores/sound tests/etc)

Also when you select Reset Scores with the fire button it jitters up and down.

https://user-images.githubusercontent.com/5980709/211690463-ec8f6eab-da9c-4c9f-a66a-7c94dac21de1.MOV

**Comment by jessaskey** [comment]
Okay, found static left position values and all set equal.

**Comment by jessaskey** [comment]
Still trying to figure out why the 'RESET SCORES' text jumps slightly when the 'SHIELD TO CONFIRM!' is on the screen.

**Comment by jessaskey** [comment]
Bryan... is this still happening on your game?

**Comment by bakerhillpins** [comment]
No the text doesn't wiggle back and forth any more.
