### ISSUE TITLE
Sound test behaves oddly

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#230]
If I go to the Gamma Test screen and start playing sounds back starting with the highest sound (x7F IIRC) and let it play then go back to lower sounds and try them. When I return to 7F it doesn't work anymore.

It seems like maybe it causes the sound board to reset as I hear the age old Atari "Speech chip test" and the reactor countdown 10-0.. Sorta like I started sound selftest on the Atari Star Wars board where it just loops through everything.

Anyway, it's hard to explain. If you need a movie I can get one. Or we can have a teams meeting.

**Comment by jessaskey** [comment]
I figured out what this issue was... the sound commands needed re-arranged a bit due to some hidden sounds. :-)
