### ISSUE TITLE
Tesseract is lost when you die.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#239]
1.01

If you play a level and pick up the Tesseract before you trigger the reactor and then die, you restart the level without the tesseract. Well it doesn't show up in the upper left corner and it IS in the level again. 

I didn't actually try setting off the reactor to see if it sends you to the secret level if you don't collect it again.

I would expect it to save the Tesseract like it would a Key.

**Comment by jessaskey** [comment]
For this one it does not save the tesser... special behavior. Im not going to fix this because I would be worried about introducing bugs.
