### ISSUE TITLE
MHTE Hint Text Error Level 1

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#241]
v1.02 Romset beta
MHPE 13790 05202023

Tournament edition Level 1 Hint Text is still garbled. 

Final TE maze design changes have been finished since May of 2023.
Still waiting for a fixed/bug free romset version so I can make a 1CC video and finish my part of this project.

Sigh.

**Comment by jessaskey** [comment]
Okay, sent these to you this past week. I verified that the Level 1 Maze hint was good so I believe I found the issue which was a compilation problem.
