### ISSUE TITLE
Make long range scanner scale evenly from level 1-28 to the end.

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#29]
Right now the long range scanner is broken down into 8 sections but for each section (level 1-3, 4-7, 8-11, etc).. the ship moves in the same segment, make the whole process linear so that within each group of 4 levels, the ship moves 25% of the major tick marks each level.

**Comment by MajorHavoc** [comment]
This is a good fix. I never went back and fixed that just because I forgot about it. 

BUT, each dot was supposed to represent a space station to the planet. Do we need more dots displayed? 

-Owen-

**Comment by jessaskey** [comment]
So in the final version there are I think 5 dots with a planet looking object at the end. Each dot was a quad of levels... so for level 1-4 you would get closer to the first dot. the levels 5-8 would be getting closer to the second dot etc. Then when you would do levels 17-20 you would be approaching the planet, but it would just reset for level 21 and put you back where you were on Level 17 and it would repeat forever that way. 

When I added the slots for new levels from 17-24, plus the homeworld, I added two more dots so for each quad, you would similarly approach the next dot and then approach the homeworld for levels 21-24. However, in my laziness at the time, I just have the ship approaching the dots the same 'pattern' for 1-4... so the ship doesn't technically get any farther for level 1 vs level 2 vs level 3 vs level 4. I just put this in there because I need to go back and inrementally make the ship move the appropriate distance between the dots based upon the individual level. 

So, it basically works now, but i needs to be corrected before final release. :-)

**Comment by jessaskey** [comment]
okay, I just implemented this fix... will release with 0.18

**Comment by jessaskey** [comment]
In attempting to do this... I caused some other problems... so in the next release I will get this fixed up. The issues in v0.18 are that the long range scanner has the wrong number of dots and that the center picture of the next ship enemy no longer scrolls down into view the way it should.

**Comment by jessaskey** [comment]
changed this up a bit to make the code simpler by using a lookup table for values rather than trying to do crazy math on the lroff variable.
