### ISSUE TITLE
Breakout blocks acting funny with multiple balls.

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#31]
During the second and third breakout sequences, the balls are behaving erratically... sometimes a ball may pass through the bricks on the way up. Sometimes when the first ball goes past the paddle, the other balls turn invisible but still act upon the bricks...

**Comment by MajorHavoc** [comment]
I still STRONGLY object to this multiball nonsense on Breakout. It really offends me actually. The game was added as a prank, and a way to earn an extra life, not to be a major play element. Lets fix this bug by just going back to one ball please.  And if and when I have time, I will write a Space Duel like game for the second round, and maybe a Tube Chase or Skydiver game for a third round. 

Thank you,
-Owen-

**Comment by jessaskey** [comment]
I think that the Space Duel mini-game in there would be fantastic. I will work with Owen so he can write code for this and if all goes well, we will get that in there. Im just going to leave the breakout as it is for now because we have bigger fish to fry before CAX.

**Comment by jessaskey** [comment]
Fixed in 0.26
