### ISSUE TITLE
Add in Credits/Thank you page

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#39]
It was forbidden in 1983 for designers to put their names into a game. That started changing a few years later so it would be nice to put in a listing of the original design team along with folks that helped with The Promised End.

**Comment by jessaskey** [comment]
This is done.... the way it is currently coded is that 25% of the time after the long story text in attract. The design team names will be shown. Once we get new mazes from folks, then I will add their names later.

**Comment by MajorHavoc** [comment]
That is correct.  The place where the story is was actually the credits screen. I suggest that every other attract mode to that area alternate between the story and the credits. So the first time you see the story. The second credits, then story, the credits etc. I always thought scrolling credits would have been cool, and I added them and was immediately told they had to be removed. 

And if space is available, maybe a little Pixar like credit fun. While credits roll, randomly things happen, like:  Havoc walks out, stands and tap his foot, and walks away. The teapot robots come out and shoot at each other as they scroll up the screen, the catastofighter flys by shooting, any of the many maze objects animates as it scrolls up the screen, etc etc

I really wanted to do all that but alas the credits were scrapped. 

I’m away until Monday, but will try and get a list of complete names, but

Owen Rubin - designer, programmer, original concept and story line, sound design, animation software, level design
Mark Cerny - designer, programmer, level design &  tuning, creative input
Lyle Rains - artist, character animation, concept, creative input, senior management
Morgan Hoff - project management, pain in the rear. (Can we say that?)
Rick Moncrief - Save the day and project manager
Doug Snyder - hardware design and engineering
Steve Calfee - department management, creative input
Mike Albaugh - coin routines, self-test routines, tools, go to problem solver
Dave Sheppard - VAX and computing support, assembler tools, production tools
????????????? - Cabinet art and graphics
????????????? - industrial design (cabinet and controls)
Need to add marketing people, but not sure who.
I’m sure there are a number of people missing 

This is a start for the original, on the updated version, I would add myself as concept storyline, creative input, and put everyone else you know. And I would put The Promised End credits first, followed by Original Game second.

Comments?
-Owen-

**Comment by jessaskey** [comment]
Okay, thanks.... this is perfect. I will use what you have above for a list of the Original team and also do the alternating thing you suggest on the attract mode.

**Comment by MajorHavoc** [comment]
The reason I suggested the other way, basically replacing the story part of the time, (and 25% of the time is fine)is that many people don't sit through the story or spin the controller and will never see it the credits.  Remember, the story is already after a long instructions screen. So credits would be after a long story, way down. 

Think about it.
-Owen-
