### ISSUE TITLE
This maze results in Endless Repeat of landing.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#48]
Running this maze in the MAME release causes the landing and dropping into the maze sequence to endlessly repeat.

So, in all fairness the OneWay and the Perkoid are not in "valid" positions so that may effect your decision to fix or not. I was testing some MazeObject placement code so I was strategically placing the maze objects by dropping with the mouse pointer at "known" reference points (specific MazeWalls endpoints)  so that I could help resolve proper Render offsets.

[Promised End Mazes.Level 2.GetsStuckInLoop.mhz.zip](https://github.com/jessaskey/mhavocpe/files/2929149/Promised.End.Mazes.Level.2.GetsStuckInLoop.mhz.zip)

**Comment by bakerhillpins** [comment]
Ok, so this isn't an issue with the changes I made to Level2. Just loading the PE ROM mazes and then launching Level 2 in MAME and it loops forever. In this case (no changes to level2) I can hear the Maxbot saying alert and the screen follows the path that Rex would take but there isn't any Rex drawn on the screen.

I'm running HBMAME64  0.205. 

Oh, it might be useful to record the MAME file version info into any error reporting or Maze file save just so we have that if/when someone reports an error.

**Comment by jessaskey** [comment]
Okay, I will check this one out tonight and see if I can duplicate it. I suppose I should try and include as much info as possible like you suggest, MAME version, Template ROM’s versions, etc.

**Comment by bakerhillpins** [comment]
Level3 - MAME just locks up. Level4 resets back to Attract mode.

There is something funky going on. I can only play level 1.

**Comment by jessaskey** [comment]
Hmmmmm… I can run Level 4 just fine, but I did notice that the Sparkoids aren’t moving. I did push several changes to the DEVELOPMENT branch (specific to maze template and files)… make sure you have that and that you only have the mhavocpe.exp file in the template folder along with the ROMs.

**Comment by bakerhillpins** [comment]
I just merged in your changes and now everything is working. Sorry about that. We can close this. DOH!

**Comment by jessaskey** [comment]
Coolio.. im working on the sparkoid bug now while we drive to denver
________________________________

**Comment by jessaskey** [comment]
Fixed in 0.26
