### ISSUE TITLE
Add in Self Test option to Double + Quadruple the LETA counter

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#52]
Scott suggested having a self test option to let the LETA multiplier be set in Self Test to overcome the challenges of folks using a Tempest Spinner. His suggestion is for the following 3 options.

1. Normal 
2. Double
3. Quadruple

**Comment by MajorHavoc** [comment]
It's a smart idea. If you have time. Be careful this does not become a
career with lots of add one.

-Owen-

**Comment by jessaskey** [comment]
Yeah, this will get put together with the Self Test code to modify settings without needing to dig into the cabinet and set the DIP switches. It is certainly a luxury item.
