### ISSUE TITLE
L13+ Transporter Vector "Static" 

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#58]
Looks like a broken glass effect on screen originating from center of some Transporters Level 13+.

**Comment by jerkyspace** [comment]
More specifically this "vector noise" centered on the Transporter happens...

When you exit the Yellow Transporter into the Reactoid room on Level 13.

When you exit the Green Transporter on Level 14 after picking up the Green Key.

When you exit the Blue Transporter on Level 14 after setting off the Reactor.

When you exit the Red Transporter on Level 15 just before IonCannon5.

When you exit the Red Transporter on Level 16 on the way to the Red Key and this "static" doesn't center on the Transporter like other ones do for some reason it's almost like it's centered on the Yellow Door above here. It also happens when you exit the set of Red Transporters after you the Red Key on the way to the Red Door.

When you exit the Green Transporter on Level 16.

**Comment by jessaskey** [comment]
Bryan and I saw this at CAX too and though we had a way to duplicate it but after CAX we were not able to get it to happen again. Have you been able to see this happen on the last maze sections? We saw it on Level 22 originally.

**Comment by jessaskey** [comment]
I think this may have gotten fixed in our last minute CAX fixes that night.

**Comment by jerkyspace** [comment]
Haven't seen any vector noise related to transporters on Level 13...but it is still really bad on Level 16 in the 0.52 romset. It usually starts on the exit of Red Transporter12. Usually very bad around Transporters 14 and 16 (Blue/Green).

I saw a little bit of it on Level 22 occasionally when exiting Cyan Transporter 33.

You don't see this when playing from the Editor...only when playing stand alone with HBMAME (0.212).

**Comment by jerkyspace** [comment]
Unfortunately (0.52 roms). I am seeing it again with HBMAME 0.209 on levels 13 and 14. On these levels you don't see it until you exit the first transporter of any pair and then it usually appears as you exit the other side.

Also seeing this on level 15 when you exit the red transporter.

Again not seeing this int he Editor when you go right to these levels.

**Comment by jessaskey** [comment]
Okay, thank you. I think we were trying from the editor, so I will go check into it now.
