### ISSUE TITLE
Level 18 "invisible wall" blocking shots from IonCannon38

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#62]

**Comment by jerkyspace** [comment]
This had been temporarily fixed an Editor version or two ago but it came back in the latest rom release 0.41

**Comment by jerkyspace** [comment]
Back in latest rom release .42. during playback...but Editor version 1.1.888.0 is good.

**Comment by jerkyspace** [comment]
Still an issue in 0.44 DEBUG DEMO romset.

**Comment by jerkyspace** [comment]
FIXED.

**Comment by jerkyspace** [comment]
Sorry. The invisible wall blocking IonCannon shots isn't there when you select this level directly...but still is when you play from Level 1 to it. Romset 0.45 DEMO.

**Comment by jerkyspace** [comment]
Still an issue in 0.52 romset. Same invisible wall at same location blocking IonCannon9 shots from going all the way down the hallway. Doesn't do this in Editor 1.2.986.2 from HBMAME though (0.212). Also doesn't do it if you select this level from demo mode. Only when you play from Level 1 to here.

**Comment by jerkyspace** [comment]
0.53 romset

So the recent change that eliminates the "invisible" vertical barrier that is part of reactor objects does help the issues with it on levels 11 and 13...but I know why they put it in originally : it makes the object feel more "real" if you bump into it like you pressed the button to set it off (same for the clock).

It also keeps the player from flying through it and into the wall behind it which is in some cases a force-field that will kill them. The button is sort of arbitrary if you just pass right through it without the invisible barrier to run into. After some play testing I feel like we need the invisible barrier at the button to make it feel right. 

So I first reworked Level 11 so you set off the reactor from the left side to avoid the getting stuck issue on that level all together (since it was in the path of the player to get out and the button was on the opposite side of them). 

I did them same to Level 27 where it was easy to flip the transporter locations around to put the reactor facing the "normal" direction (button on left side where player approaches from).

Level 13 is not such an easy fix. I can't flip the level around so the reactor button is on the same side as the player approaches it because the maze is so small and the location of the entrance prevents this. I can't get the reactor facing the right way without a major design change to do so.

One solution might just be making a new right sided button version object just for Level 13 (or have it be a parameter for which side the button faces)? That way the button will be facing the correct direction and you could still use the invisible barrier to make the player feel like the pressed the button (button on right side for Level 13 and adjust inviso vertical barrier accordingly)? 

If possible too maybe adjust the invisible barrier parameters so it's not just a single invisible line but a box or the outline of the reactor so players can't jump into it anymore and get stuck? (with two vertical sides and a horizontal top). That way the player would never fall into the object again (but does not fix the button on the wrong side issue on level 13).

Maybe do the same for the clock so you cannot jump into it and get stuck too like happens on Level 21 sometimes?

The only other way to "fix" the level 13 reactor issue is to allow transporters facing the same direction for just this level. Then I could just flip the objects around at the bottom of the maze to get the reactor button facing to the left side where the player comes at it from.

Thoughts?

**Comment by jerkyspace** [comment]
0.58 romset
HBAME 0.209

Same issue when playing from 1>18 (including secret levels). The IonCannon (cannon12 now) shots terminate into an invisible wall in the hallway right below the Blue Transporter30.

Don't see the same in Editor v1.2.1064.0.

**Comment by jessaskey** [comment]
I have hopes that #172 was causing this as a side effect, but for now Im going to keep this open until I can confirm.

**Comment by jessaskey** [comment]
Fixed for sure now.
