### ISSUE TITLE
Player ship appears at start of Level 20 but nothing else happens

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#63]

**Comment by jerkyspace** [comment]
Still broken in romset playback 0.42.

Loads fine in Editor version 1.1.888.0

**Comment by jerkyspace** [comment]
Same issue in 0.44 DEBUG DEMO romset.

**Comment by jerkyspace** [comment]
Still a problem in 0.45 romset whether you select the level from Demo mode or play up to it from 1-19 or any combination of levels before it. Does the same thing in NON-DEMO mode romset.

It gets stuck with the fighter sitting on the screen. Nothing loads after that :(

**Comment by jessaskey** [comment]
I fixed this pre-CAX...so it should be good as of v.50.. maybe even .48 or .49
