### ISSUE TITLE
Level 24 maze won't load

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#66]
Star Castle battle begins but no enemies nor wall sections. Cube just sits at top of screen and does nothing. Maze never loads even when bonus timer runs out.

**Comment by jerkyspace** [comment]
Still get this in rom playback 0.42.

Using the transporter fixed maze collection in Editor 1.1.888.0 I get :

[ERROR] Unmatched Transporter : Transporter 48. Expected matching flashing Transporter in Maze.

That's without changing anything right from the mhc you sent me.

**Comment by jerkyspace** [comment]
Also doing this in DEMO romset 24 only when you select this level directly in Demo Mode from the start of the game.

**Comment by jessaskey** [comment]
This is sort of expected behavior if starting directly on Level 24, those sections of the final maze need to play in sequence so you really need to start from Level 21 to test them out for now.
