### ISSUE TITLE
Level 26 IonCannon issues return

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#67]
I am pretty sure these were "fixed" in the last round of changes you guys made to restore all the problem IonCannons back to normal. But now the Level 26 cannons are moving too far horizontally and missing their intended target key shafts like in the playback video I shared. If you can fix these however you did before great. Otherwise let me know if I have to adjust the programs myself. No changes have been made to this level since the last round of issues.

**Comment by jessaskey** [comment]
I think what may have happened here is that Bryan 'converted' the old incorrect IonCannon pauses and had a fixed .mhc file... but Im wondering if you have an older 'non-fixed' version that is coming back now... did you get a new .mhc from Bryan at some point and switch over to that one or am I misunderstanding?

**Comment by jessaskey** [comment]
Looking at the Cannon programs, there seem to be lots of 'extra' moves in there... seems like these are out of whack?

![image](https://user-images.githubusercontent.com/3683098/61249397-61964a00-a712-11e9-9c09-0c2ffb375f9f.png)

**Comment by jerkyspace** [comment]
Will check this out tomorrow...but Marc Cerny used something similar on old
rev 3 level 16...now 20.

It moves the cannon one small "grid" at a time instead of one big move with
a longer waitframe time.

Seems like he knew how far that smaller move would be a multiplied it out
like animation steps or maybe it was easier to get exactly how he wanted it.

That's where I got the idea anyway. There still may be too many of them and
I will check it out when I get home.

Flying out of Logan soon and looking forward to seeing you all at CAX!

**Comment by jerkyspace** [comment]
Well it looks like all I had to do was divide the wait frame times for movement and pauses by 4...for all 120 instances of them for both cannons by hand. Go figure. FIXED.

**Comment by jessaskey** [comment]
okay, thank you.... I will mark this as closed and move it out of testing now.

**Comment by jerkyspace** [comment]
Sorry my bad. I had to re-open this because it still does it when you 
play up to this level from Level 1 (does not in Demo Mode Level Select 
though).
