### ISSUE TITLE
Breakout game issues

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#70]
You still have balls disappear that sometimes keep playing out of view for a few moments. Happens mostly when you more than one ball in play and first ball gets past player...others vanish right away...but sometimes those ones keep playing and taking out blocks until it falls past player or timer runs out for minigame.

You can keep making the ball appear over and over if you move your paddle out of the way. Just keep pressing firing and balls come out one after another after another if you keep letting them go by until internal timer for this mini game expires (for warp code entry).

**Comment by jessaskey** [comment]
I went through and audited this code a bit so hopefully things are working better now. I decreased the max number of balls down to 2 for now as well.
