### ISSUE TITLE
Maze doors are 'Open' after intra-level Transport

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#76]
When transporting from Level 21 to Level 22, the maze doors are open, they should be closed.

**Comment by jerkyspace** [comment]
Hmmm...I have not seen this behavior via the roms nor the Editor stand alone. I will keep an eye out for it.

**Comment by jessaskey** [comment]
It only happens on ROMs 0.42 during an Intra-Level transport. This will be fixed in 0.43 release.

**Comment by jerkyspace** [comment]
Fixed as far as I can tell.
