### ISSUE TITLE
Max Robots should die when hit with Trip Pad Pyroid

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#77]
When a Max robot is killed via a Trip Pad Pyroid, it should die and explode in a somewhat dramatic fashion.

**Comment by jerkyspace** [comment]
Ion Cannon shot or TripPad Fryoids? I still like the Trippad shot idea personally.

None of the current Maxoid levels have any IonCannons while they have been set up to lure Maxoids into the path of TripPad shots.

**Comment by jessaskey** [comment]
Whoops... you are right about this one... I changed it to be Trip Pad Pyroid instead of Ion Cannon Shot.

**Comment by jerkyspace** [comment]
I feel like it should take more than one shot to destroy them especially if we are still giving out 9999 points or something significant. I can let the player know in maze hints too (Level 25 and 27).

Maybe 3-5 "shots" to destroy them? Change Maxoid color to indicate damage state? Single and Double TripPad Fryoids should count as one "shot" I think. 

Thoughts?

**Comment by jessaskey** [comment]
Once I get into coding this, we can figure out potential ideas.... there are certainly limitations on the coding side... I don't expect to get to this before CAX unfortunately.

**Comment by jessaskey** [comment]
Im working on this now... a couple notes... I can't do multiple shots to kill Max right now, so Im going to get this working with a single shot and we can expand if needed later. Also, I feel like there should be some kind of effect when Max dies along with a speech sound. I will create those as separate features once this is done tho.

**Comment by jessaskey** [comment]
here is how I have it working now...  Max and Trip Pad Pyroid both die when a collision happens.. pyroid will make the 'splash' sound that it makes when it hits a wall and do the 'splash' animation too... Max will do a 'uuuuughhh' sound for now. If you think of some good short phrases that I can randomize with, I can record those too.
