### ISSUE TITLE
Reset Shields After Flashing Transporters on Level 21-24?

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#88]
Not sure if we ever considered this but if you use your shields up on Level 21 for example...you have no shields for the rest of 22-24.

Maybe we should reset them when passing through Flashing Transporters to next section? Or just one charge of shields for all of 21-24?

**Comment by jessaskey** [comment]
Maybe the number of hits should just increase for the whole scenario or do you think it would actually just work better to reset them in each section? Either one is pretty straightforward to do, you can give best guidance on gameplay tho.

**Comment by jerkyspace** [comment]
Resetting them for now might be easier for the player to follow with the existing rules (can absorb 4 smaller shots or one big shot). Otherwise we would need to put up another maze hint to explain to them the new parameters/number of shots they can take.

**Comment by jessaskey** [comment]
Okay, this is now set up to restore fully after each flashing transporter.
