### ISSUE TITLE
After you finish Level 28 the game breaks

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#93]
After you play through the Hidden levels 25-28 the game tries to load a broken Level 29 and gets hung up.

Back to Level 1 or Demo Level Select?

**Comment by jessaskey** [comment]
Thanks for logging this.. maybe I will try and do a fast  'Yay... You reached the homeworld!' text page and award 500,000 points or something before CAX.
________________________________

**Comment by jessaskey** [comment]
For now if you play level 28 it will just wrap back to Level 1... since Level 28 will be a hidden level, that is fine for now.
