### ISSUE TITLE
Demo Mode Level Select of Level 26-28 gives huge "warp" bonus scores

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#94]
When using Demo Mode Level Select : 

Level 25 awards 1,200,000 points

Level 26 awards 59,200,000 points.

Level 27 awards 4C,E60,000 points (1,290,141,696).

Level 28 awards D3,0F0,000 points (3,540,975,616).

I know we promised "more points" but this is a bit too much don't you think?

**Comment by jessaskey** [comment]
Fixed pre-CAX 2019
