### ISSUE TITLE
Extra Red Door on Level 22/Not appearing where it is drawn

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#95]
The extra red door on Level 22 is draw off the map in the romset you gave me...but when playing the Demo Debug romset 0.47 the red door appears just after the flashing transporter door and the transporter to level 23. Seems like an Editor bug?

It should be off the map just like it is drawn (new location now)...otherwise it uses up the red key too soon (no red key at the start of Level 23 now). 

Please move this red door back off the map and double check the level because it doesn't always end up where it is drawn in the editor when you play it back in HBAME (I had it end up randomly back in the maze several b4 I found a location that did not trip up the Editor).

**Comment by jessaskey** [comment]
Okay, I moved this into a place where they don't get into the main maze play area. They are visible outside the maze but that will have to be good enough for CAX which should be fine. We will have to do some research on why these wrap into a funky spot and how we can limit them from being placed into 'bad' spots.

**Comment by jessaskey** [comment]
The temp fix will be in v0.48
