### ISSUE TITLE
Level 21 IonCannon shots disappearing

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#99]
Playing from Level 17 forward in Demo Mode 0.48...

When I got to Level 21 the IonCannon18 shots were vanishing before they reached the end of the hallway (right at the end of the ceiling above them before the opening to come down into this hallway).

It's a slightly different version of the bug I reported in the Editor linked below.
https://github.com/jessaskey/mhedit/issues/76

**Comment by jerkyspace** [comment]
This behavior is intermittent and maybe depends on where you play up to before this level/where you die on 22-24. It seems okay when you select this level directly in Demo mode.

**Comment by jessaskey** [comment]
We figured this out at CAX to be a transporter issue but as you know, you moved around some things so it wouldn't make Level 21 unpassable. So, I will keep investigating this post CAX now and hopefully come up with a solution in quick time.

**Comment by jerkyspace** [comment]
0.52 Romset
0.212 HBMAME

Still seeing this when playing from level 1 to 21.

**Comment by jerkyspace** [comment]
0.58 romset
0.209 HBAME

Still an issue when playing from Level 1-21.

**Comment by jessaskey** [comment]
Okay, still trying to investigate this and get it consistently. I wonder Jerky if you can send me a MAME gamesave so I can try and resume from the same spot to see what is happening?

**Comment by jessaskey** [comment]
I have hopes that #172 was causing this as a side effect, but for now Im going to keep this open until I can confirm.

**Comment by jessaskey** [comment]
Fixed for sure now
